name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: rg-eshoponweb-Lab
  LOCATION: germanywestcentral
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 135aee60-f0b2-444a-b29a-e16361ecb782
  WEBAPP-NAME: eshoponweb-webapp-Lab

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Check Resource Group
        run: |
          az group show --name ${{ env.RESOURCE-GROUP }} || az group create --name ${{ env.RESOURCE-GROUP }} --location ${{ env.LOCATION }}
      - name: List existing WebApps
        run: az webapp list --query "[].{Name:name, ResourceGroup:resourceGroup}" --output table
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: ./bicep-template/$(basename ${{ env.TEMPLATE-FILE }})
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          deploymentMode: Incremental
          failOnStdErr: false
      - name: Publish Website to WebApp
        run: |
          for i in {1..5}; do
            az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip && break || sleep 30
          done
